/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Fri Jun 23 12:05:08 2006
 * Arguments: "-B" "macro_default" "-B" "csharedlib:libbploopyUse" "-W"
 * "lib:libbploopyUse" "-T" "link:lib" "bploopyUse.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_libbploopyUse_public_data[] = {'3', '0', '8', '1',
                                                         '9', 'D', '3', '0',
                                                         '0', 'D', '0', '6',
                                                         '0', '9', '2', 'A',
                                                         '8', '6', '4', '8',
                                                         '8', '6', 'F', '7',
                                                         '0', 'D', '0', '1',
                                                         '0', '1', '0', '1',
                                                         '0', '5', '0', '0',
                                                         '0', '3', '8', '1',
                                                         '8', 'B', '0', '0',
                                                         '3', '0', '8', '1',
                                                         '8', '7', '0', '2',
                                                         '8', '1', '8', '1',
                                                         '0', '0', 'C', '4',
                                                         '9', 'C', 'A', 'C',
                                                         '3', '4', 'E', 'D',
                                                         '1', '3', 'A', '5',
                                                         '2', '0', '6', '5',
                                                         '8', 'F', '6', 'F',
                                                         '8', 'E', '0', '1',
                                                         '3', '8', 'C', '4',
                                                         '3', '1', '5', 'B',
                                                         '4', '3', '1', '5',
                                                         '2', '7', '7', 'E',
                                                         'D', '3', 'F', '7',
                                                         'D', 'A', 'E', '5',
                                                         '3', '0', '9', '9',
                                                         'D', 'B', '0', '8',
                                                         'E', 'E', '5', '8',
                                                         '9', 'F', '8', '0',
                                                         '4', 'D', '4', 'B',
                                                         '9', '8', '1', '3',
                                                         '2', '6', 'A', '5',
                                                         '2', 'C', 'C', 'E',
                                                         '4', '3', '8', '2',
                                                         'E', '9', 'F', '2',
                                                         'B', '4', 'D', '0',
                                                         '8', '5', 'E', 'B',
                                                         '9', '5', '0', 'C',
                                                         '7', 'A', 'B', '1',
                                                         '2', 'E', 'D', 'E',
                                                         '2', 'D', '4', '1',
                                                         '2', '9', '7', '8',
                                                         '2', '0', 'E', '6',
                                                         '3', '7', '7', 'A',
                                                         '5', 'F', 'E', 'B',
                                                         '5', '6', '8', '9',
                                                         'D', '4', 'E', '6',
                                                         '0', '3', '2', 'F',
                                                         '6', '0', 'C', '4',
                                                         '3', '0', '7', '4',
                                                         'A', '0', '4', 'C',
                                                         '2', '6', 'A', 'B',
                                                         '7', '2', 'F', '5',
                                                         '4', 'B', '5', '1',
                                                         'B', 'B', '4', '6',
                                                         '0', '5', '7', '8',
                                                         '7', '8', '5', 'B',
                                                         '1', '9', '9', '0',
                                                         '1', '4', '3', '1',
                                                         '4', 'A', '6', '5',
                                                         'F', '0', '9', '0',
                                                         'B', '6', '1', 'F',
                                                         'C', '2', '0', '1',
                                                         '6', '9', '4', '5',
                                                         '3', 'B', '5', '8',
                                                         'F', 'C', '8', 'B',
                                                         'A', '4', '3', 'E',
                                                         '6', '7', '7', '6',
                                                         'E', 'B', '7', 'E',
                                                         'C', 'D', '3', '1',
                                                         '7', '8', 'B', '5',
                                                         '6', 'A', 'B', '0',
                                                         'F', 'A', '0', '6',
                                                         'D', 'D', '6', '4',
                                                         '9', '6', '7', 'C',
                                                         'B', '1', '4', '9',
                                                         'E', '5', '0', '2',
                                                         '0', '1', '1', '1'
                                                         , '\0'};

const char *__MCC_libbploopyUse_name_data = "libbploopyUse";

const char *__MCC_libbploopyUse_root_data = "";

const unsigned char __MCC_libbploopyUse_session_data[] = {'0', '0', '8', '9',
                                                          '0', '3', 'C', 'E',
                                                          '1', 'F', '7', '1',
                                                          '7', '4', '2', 'C',
                                                          '6', 'D', 'C', 'A',
                                                          'E', 'C', 'E', '0',
                                                          'A', '4', 'A', 'F',
                                                          'A', 'B', '3', 'F',
                                                          'D', 'D', '0', '2',
                                                          '8', '2', 'A', '8',
                                                          '4', '6', '6', 'A',
                                                          '1', '4', '7', 'F',
                                                          'D', '7', '4', '2',
                                                          'B', 'D', '2', 'D',
                                                          '9', '2', '2', 'B',
                                                          'D', '1', '0', 'F',
                                                          'F', 'E', '5', 'D',
                                                          '4', 'A', 'C', 'C',
                                                          '8', '4', '7', 'C',
                                                          '4', '3', '7', 'D',
                                                          '3', '2', '8', 'B',
                                                          'E', '7', '6', '4',
                                                          'E', 'E', '3', 'D',
                                                          '0', '0', '2', '5',
                                                          '9', '4', '5', '9',
                                                          '1', '4', '7', '9',
                                                          '2', '1', 'F', 'B',
                                                          '7', 'E', '3', '9',
                                                          '9', '2', 'A', 'A',
                                                          '9', '6', '1', 'A',
                                                          'C', '5', 'C', 'E',
                                                          'B', 'E', 'D', '4',
                                                          '1', 'F', '1', 'C',
                                                          '0', 'D', 'A', 'B',
                                                          'B', '0', 'E', '6',
                                                          'C', '2', '9', '4',
                                                          'D', 'A', '2', '8',
                                                          '4', '0', '9', '5',
                                                          'B', '2', '0', 'B',
                                                          '7', 'B', '6', '7',
                                                          '2', '0', 'D', '3',
                                                          'A', '9', 'E', '8',
                                                          '7', 'B', 'A', '4',
                                                          '2', '2', '0', 'F',
                                                          '7', '1', '3', '0',
                                                          '6', '2', '4', 'C',
                                                          '9', '2', 'D', '9',
                                                          '4', '0', '2', 'C',
                                                          'C', 'D', '5', '7',
                                                          'F', '3', '2', '5',
                                                          'C', 'A', 'C', 'D',
                                                          'F', '2', '4', 'F',
                                                          '1', '6', 'E', 'F',
                                                          '6', '0', '2', '2',
                                                          'F', '4', '3', '4',
                                                          'C', '7', '5', 'E',
                                                          '8', '6', '5', '4',
                                                          'B', 'F', '3', 'B',
                                                          '2', '0', 'B', '4',
                                                          'E', 'E', '9', 'C',
                                                          '7', '0', '6', 'C',
                                                          'A', 'D', '6', '5',
                                                          'A', '8', 'E', '3',
                                                          '1', 'A', '2', '8'
                                                          , '\0'};

const char *__MCC_libbploopyUse_matlabpath_data[] = {"libbploopyUse/",
                                                     "toolbox/compiler/deploy/",
                                                     "Documents and Settings/max/My Documents/Visual Studio Projects/SketchDev/CRF - Matlab/BPMRF2/",
                                                     "Documents and Settings/max/My Documents/Visual Studio Projects/SketchDev/CRF - Matlab/BPlattice2/MPI/",
                                                     "Documents and Settings/max/My Documents/Visual Studio Projects/SketchDev/CRF - Matlab/KPMtools/",
                                                     "$TOOLBOXMATLABDIR/general/",
                                                     "$TOOLBOXMATLABDIR/ops/",
                                                     "$TOOLBOXMATLABDIR/lang/",
                                                     "$TOOLBOXMATLABDIR/elmat/",
                                                     "$TOOLBOXMATLABDIR/elfun/",
                                                     "$TOOLBOXMATLABDIR/specfun/",
                                                     "$TOOLBOXMATLABDIR/matfun/",
                                                     "$TOOLBOXMATLABDIR/datafun/",
                                                     "$TOOLBOXMATLABDIR/polyfun/",
                                                     "$TOOLBOXMATLABDIR/funfun/",
                                                     "$TOOLBOXMATLABDIR/sparfun/",
                                                     "$TOOLBOXMATLABDIR/scribe/",
                                                     "$TOOLBOXMATLABDIR/graph2d/",
                                                     "$TOOLBOXMATLABDIR/graph3d/",
                                                     "$TOOLBOXMATLABDIR/specgraph/",
                                                     "$TOOLBOXMATLABDIR/graphics/",
                                                     "$TOOLBOXMATLABDIR/uitools/",
                                                     "$TOOLBOXMATLABDIR/strfun/",
                                                     "$TOOLBOXMATLABDIR/imagesci/",
                                                     "$TOOLBOXMATLABDIR/iofun/",
                                                     "$TOOLBOXMATLABDIR/audiovideo/",
                                                     "$TOOLBOXMATLABDIR/timefun/",
                                                     "$TOOLBOXMATLABDIR/datatypes/",
                                                     "$TOOLBOXMATLABDIR/verctrl/",
                                                     "$TOOLBOXMATLABDIR/codetools/",
                                                     "$TOOLBOXMATLABDIR/helptools/",
                                                     "$TOOLBOXMATLABDIR/winfun/",
                                                     "$TOOLBOXMATLABDIR/demos/",
                                                     "$TOOLBOXMATLABDIR/timeseries/",
                                                     "$TOOLBOXMATLABDIR/hds/",
                                                     "toolbox/local/",
                                                     "toolbox/compiler/",
                                                     "toolbox/optim/"};
const int __MCC_libbploopyUse_matlabpath_data_count = 38;

const char *__MCC_libbploopyUse_classpath_data[] = { "" };
const int __MCC_libbploopyUse_classpath_data_count = 0;

const char *__MCC_libbploopyUse_lib_path_data[] = { "" };
const int __MCC_libbploopyUse_lib_path_data_count = 0;

const char *__MCC_libbploopyUse_mcr_application_options[] = { "" };
const int __MCC_libbploopyUse_mcr_application_option_count = 0;
const char *__MCC_libbploopyUse_mcr_runtime_options[] = { "" };
const int __MCC_libbploopyUse_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


